# --- Font ---
font_family      Google Sans Code
font_size        12.0
# Kitty handles height differently, 15% increase approx
adjust_line_height 115% 

# --- Theme & Appearance ---
#include themes/Nvim_Dark.conf
background_opacity 0.75
background_blur 20
# window-decoration = true (Default in Kitty)
hide_window_decorations no
#linux_display_server wayland # or x11

# --- Keybindings ---
# Tabs
map ctrl+shift+t launch --type=tab --cwd=current
map ctrl+shift+q close_window

# Splitting
map ctrl+shift+equal launch --location=hsplit --cwd=current
map ctrl+shift+minus launch --location=vsplit --cwd=current
# Note: For strict 'right/down' mapping, specialized layouts are needed.
# This uses the default kitty split mapping.

# Navigation
map ctrl+shift+h neighboring_window left
map ctrl+shift+l neighboring_window right
map ctrl+shift+k neighboring_window up
map ctrl+shift+j neighboring_window down

# --- Behavior ---
# Inherit working directory
map ctrl+shift+n launch --cwd=current --type=os-window
enabled_layouts splits,stack

# Cursor
cursor_shape block
cursor_blink_interval 0.5
shell_integration no-cursor

cursor_beam_thickness 1.5
cursor_underline_thickness 2.0
# When the window is NOT focused, show a hollow box
cursor_shape_unfocused hollow

# Keep it on the bottom
tab_bar_edge bottom
# Make it look clean and integrated
tab_bar_style       powerline
tab_powerline_style slanted
tab_title_template  "{index}: {title}"
# Optional: Make the active tab pop a bit more
active_tab_font_style   bold
inactive_tab_font_style normal


#include current-theme.conf
include nvim-dark.conf


# BEGIN_KITTY_THEME
# Corvine
include current-theme.conf
# END_KITTY_THEME